### ISSUE TITLE
README.md doesn't follow the standard.

### ISSUE THREAD

**Issue by vimleshkumarkanaujiya** [kamalsingh2000/web-scraping-using-python-and-data-dump-to-database#1]
lease change it from "**web-scraping-using-python-and-data-dump-to-database**" to "**Web Scraping Using Python and Data Dump to Database**"

**Comment by kamalsingh2000** [comment]
Okay 👍

**Comment by vimleshkumarkanaujiya** [comment]
The issue was resolved, so closing the matter.
